FROM node:14.19.0

# Create app directory
WORKDIR /usr/src/app

COPY package*.json ./

# RUN npm install
# If you are building your code for production
RUN npm ci --only=production

COPY . .
CMD [ "node", "main.js" ]